/**
 * Specification Skill para OpenCode
 * 
 * Este skill permite gestionar especificaciones del proyecto
 * siguiendo la metodología SDD (Spec-Driven Development).
 */

export const name = "spec";
export const description = "Specification management for Spec-Driven Development";

import { writeFileSync, readFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';

const SPECKIT_DIR = '.speckit';
const MEMORY_DIR = join(SPECKIT_DIR, 'memory');

/**
 * Asegurar que los directorios existen
 */
function ensureDirs() {
  if (!existsSync(SPECKIT_DIR)) {
    mkdirSync(SPECKIT_DIR, { recursive: true });
  }
  if (!existsSync(MEMORY_DIR)) {
    mkdirSync(MEMORY_DIR, { recursive: true });
  }
}

/**
 * Crear o actualizar la constitución del proyecto
 * @param {Object} params - Parámetros
 * @param {string} params.principles - Principios del proyecto
 * @param {string[]} params.rules - Reglas a seguir
 */
export async function setConstitution({ principles, rules = [] }) {
  ensureDirs();
  
  const content = `# Project Constitution

## Core Principles

${principles}

## Rules

${rules.map((r, i) => `${i + 1}. ${r}`).join('\n')}

---
*Generated by SDD Template - ${new Date().toISOString()}*
`;

  const filePath = join(MEMORY_DIR, 'constitution.md');
  writeFileSync(filePath, content);

  console.log(`📜 Constitution saved to ${filePath}`);
  
  return {
    saved: true,
    path: filePath,
    message: "Project constitution has been saved"
  };
}

/**
 * Obtener la constitución actual
 */
export async function getConstitution() {
  const filePath = join(MEMORY_DIR, 'constitution.md');
  
  if (!existsSync(filePath)) {
    return {
      exists: false,
      message: "No constitution found. Use setConstitution to create one."
    };
  }

  const content = readFileSync(filePath, 'utf-8');
  return {
    exists: true,
    content,
    path: filePath
  };
}

/**
 * Crear o actualizar la especificación del proyecto
 * @param {Object} params - Parámetros
 * @param {string} params.title - Título del proyecto
 * @param {string} params.description - Descripción
 * @param {string[]} params.requirements - Requisitos funcionales
 * @param {string[]} params.nonFunctional - Requisitos no funcionales
 * @param {string} params.stack - Stack tecnológico
 */
export async function setSpecification({ title, description, requirements = [], nonFunctional = [], stack = "" }) {
  ensureDirs();
  
  const content = `# ${title}

## Description

${description}

## Functional Requirements

${requirements.map((r, i) => `- FR${i + 1}: ${r}`).join('\n')}

## Non-Functional Requirements

${nonFunctional.map((r, i) => `- NFR${i + 1}: ${r}`).join('\n')}

## Technology Stack

${stack}

---
*Generated by SDD Template - ${new Date().toISOString()}*
`;

  const filePath = join(MEMORY_DIR, 'specification.md');
  writeFileSync(filePath, content);

  console.log(`📋 Specification saved to ${filePath}`);
  
  return {
    saved: true,
    path: filePath,
    message: "Project specification has been saved"
  };
}

/**
 * Obtener la especificación actual
 */
export async function getSpecification() {
  const filePath = join(MEMORY_DIR, 'specification.md');
  
  if (!existsSync(filePath)) {
    return {
      exists: false,
      message: "No specification found. Use setSpecification to create one."
    };
  }

  const content = readFileSync(filePath, 'utf-8');
  return {
    exists: true,
    content,
    path: filePath
  };
}

/**
 * Crear o actualizar el plan técnico
 * @param {Object} params - Parámetros
 * @param {string} params.architecture - Descripción de la arquitectura
 * @param {string[]} params.phases - Fases del proyecto
 * @param {string[]} params.milestones - Hitos importantes
 */
export async function setPlan({ architecture, phases = [], milestones = [] }) {
  ensureDirs();
  
  const content = `# Technical Plan

## Architecture

${architecture}

## Phases

${phases.map((p, i) => `### Phase ${i + 1}: ${p}`).join('\n\n')}

## Milestones

${milestones.map((m, i) => `- [ ] M${i + 1}: ${m}`).join('\n')}

---
*Generated by SDD Template - ${new Date().toISOString()}*
`;

  const filePath = join(MEMORY_DIR, 'plan.md');
  writeFileSync(filePath, content);

  console.log(`📊 Plan saved to ${filePath}`);
  
  return {
    saved: true,
    path: filePath,
    message: "Technical plan has been saved"
  };
}

/**
 * Crear o actualizar las tareas
 * @param {Object} params - Parámetros
 * @param {string[]} params.tasks - Lista de tareas
 */
export async function setTasks({ tasks = [] }) {
  ensureDirs();
  
  const content = `# Tasks

## Pending

${tasks.map((t, i) => `- [ ] T${i + 1}: ${t}`).join('\n')}

## In Progress

## Completed

---
*Generated by SDD Template - ${new Date().toISOString()}*
`;

  const filePath = join(MEMORY_DIR, 'tasks.md');
  writeFileSync(filePath, content);

  console.log(`✅ Tasks saved to ${filePath}`);
  
  return {
    saved: true,
    path: filePath,
    message: "Tasks have been saved"
  };
}

// Exportar todas las funciones como herramientas
export const tools = {
  setConstitution: {
    description: "Create or update the project constitution with principles and rules",
    parameters: {
      type: "object",
      properties: {
        principles: {
          type: "string",
          description: "Core principles of the project"
        },
        rules: {
          type: "array",
          items: { type: "string" },
          description: "Rules to follow in the project"
        }
      },
      required: ["principles"]
    }
  },
  getConstitution: {
    description: "Get the current project constitution",
    parameters: {
      type: "object",
      properties: {}
    }
  },
  setSpecification: {
    description: "Create or update the project specification",
    parameters: {
      type: "object",
      properties: {
        title: {
          type: "string",
          description: "Project title"
        },
        description: {
          type: "string",
          description: "Project description"
        },
        requirements: {
          type: "array",
          items: { type: "string" },
          description: "Functional requirements"
        },
        nonFunctional: {
          type: "array",
          items: { type: "string" },
          description: "Non-functional requirements"
        },
        stack: {
          type: "string",
          description: "Technology stack"
        }
      },
      required: ["title", "description"]
    }
  },
  getSpecification: {
    description: "Get the current project specification",
    parameters: {
      type: "object",
      properties: {}
    }
  },
  setPlan: {
    description: "Create or update the technical plan",
    parameters: {
      type: "object",
      properties: {
        architecture: {
          type: "string",
          description: "Architecture description"
        },
        phases: {
          type: "array",
          items: { type: "string" },
          description: "Project phases"
        },
        milestones: {
          type: "array",
          items: { type: "string" },
          description: "Important milestones"
        }
      },
      required: ["architecture"]
    }
  },
  setTasks: {
    description: "Create or update the task list",
    parameters: {
      type: "object",
      properties: {
        tasks: {
          type: "array",
          items: { type: "string" },
          description: "List of tasks"
        }
      },
      required: ["tasks"]
    }
  }
};
